name       : pencil
version    : 3.1.0
release    : 4
source     :
    - https://github.com/evolus/pencil/archive/v3.1.0.tar.gz : e14eddd0aad28919cfdf8d47b726f9c75a3a0d2042605e8da96309c23a995f44
license    : GPL-2.0
component  : multimedia.graphics
networking : yes
summary    : An open-source GUI prototyping tool
description: |
    Pencil is built for the purpose of providing a free and open-source GUI prototyping tool that people can easily install and use to create mockups in popular desktop platforms.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xi)
    - pkgconfig(xkbfile)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - git
    - nodejs
setup      : |
    %patch -p1 < $pkgfiles/0001-pencil-only-build-x64-and-tar.gz-for-linux.patch
    # Yes, a Windows patch is needed otherwise electron-builder reports a configuration error. GG.
    %patch -p1 < $pkgfiles/Fix-Electrons-Windows-configuration.patch
build      : |
    npm config set unsafe-perm=true
    npm install
    npm run dist:linux
install    : |
    install -Dm644 $workdir/build/icon.png $installdir/usr/share/pixmaps/pencil.png
    install -Dm644 $pkgfiles/pencil.desktop $installdir/usr/share/applications/pencil.desktop

    install -dm755 $installdir/usr/share/pencil/
    cp -r $workdir/dist/linux-unpacked/* $installdir/usr/share/pencil/

    install -dm755 $installdir/usr/bin
    ln -sv /usr/share/pencil/pencil $installdir/usr/bin/pencil
