name       : pencil
version    : 3.0.4
release    : 2
source     :
    - https://github.com/evolus/pencil/archive/v3.0.4.tar.gz : f00b06d7db9583479597db827ebe1371ad0878a947a28c97c00895e50f2476f4
license    : GPL-2.0
component  : multimedia.graphics
networking : yes
summary    : An open-source GUI prototyping tool
description: |
    Pencil is built for the purpose of providing a free and open-source GUI prototyping tool that people can easily install and use to create mockups in popular desktop platforms.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xi)
    - pkgconfig(xkbfile)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - git
    - nodejs
setup      : |
    %patch -p1 < $pkgfiles/0001-pencil-only-build-x64-and-tar.gz-for-linux.patch
build      : |
    npm config set unsafe-perm=true
    npm install
    npm run dist:linux
install    : |
    install -Dm644 $workdir/build/icon.png $installdir/usr/share/pixmaps/pencil.png
    install -Dm644 $pkgfiles/pencil.desktop $installdir/usr/share/applications/pencil.desktop

    install -dm755 $installdir/usr/share/pencil/
    cp -r $workdir/dist/linux-unpacked/* $installdir/usr/share/pencil/

    install -dm755 $installdir/usr/bin
    ln -sv /usr/share/pencil/pencil $installdir/usr/bin/pencil
